# Generated by Django 5.1.3 on 2024-11-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercisemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='reps',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='rest',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='sets',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
