# Generated by Django 5.1.3 on 2024-11-28 22:16

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercisemodel_reps_exercisemodel_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='muscle_groups',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('QP', 'Quadriceps'), ('HS', 'Hamstring'), ('SH', 'Shoulder'), ('TP', 'Triceps'), ('BP', 'Biceps'), ('FA', 'Forearm'), ('GM', 'Gluteus maximus'), ('CV', 'Calves'), ('CT', 'Chest'), ('BK', 'Back'), ('AB', 'Abs')], max_length=2),
        ),
    ]
