# Generated by Django 5.1.3 on 2024-11-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exercisemodel_muscle_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='muscle_groups',
            field=models.CharField(choices=[('QP', 'Quadriceps'), ('HS', 'Hamstring'), ('SH', 'Shoulder'), ('TP', 'Triceps'), ('BP', 'Biceps'), ('FA', 'Forearm'), ('GM', 'Gluteus maximus'), ('CV', 'Calves'), ('CT', 'Chest'), ('BK', 'Back'), ('AB', 'Abs')], max_length=2),
        ),
    ]
