# Generated by Django 5.1.3 on 2024-11-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('technique', models.TextField()),
                ('muscle_groups', models.CharField(choices=[('QP', 'Quadriceps'), ('HS', 'Hamstring'), ('FD', 'Front deltoids'), ('SD', 'Side deltoids'), ('RD', 'Rear deltoids'), ('TP', 'Triceps'), ('BP', 'Biceps'), ('FA', 'Forearm'), ('GM', 'Gluteus maximus'), ('CV', 'Calves'), ('CT', 'Chest'), ('BK', 'Back'), ('AB', 'Abdominals')], max_length=2)),
                ('image', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
