# Generated by Django 5.1.3 on 2024-12-05 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworkoutmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_workouts', to='accounts.profile'),
        ),
    ]
