# Generated by Django 5.1.3 on 2024-12-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworkoutexercisemodel',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_exercise', to='exercises.exercisemodel'),
        ),
    ]
