# Generated by Django 5.1.3 on 2024-12-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0002_alter_customworkoutexercisemodel_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworkoutexercisemodel',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercise', to='exercises.exercisemodel'),
        ),
        migrations.AlterField(
            model_name='customworkoutexercisemodel',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to='workouts.customworkoutmodel'),
        ),
    ]
