# Generated by Django 5.1.3 on 2024-11-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0003_exercisemodel_reps_exercisemodel_rest_and_more'),
        ('workouts', '0002_delete_exercisemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWorkoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(related_name='exercises', to='exercises.exercisemodel')),
            ],
        ),
    ]
