# Generated by Django 5.1.3 on 2024-11-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercisemodel_reps_exercisemodel_rest_and_more'),
        ('workouts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworkoutmodel',
            name='exercises',
            field=models.ManyToManyField(related_name='custom_workout_exercises', to='exercises.exercisemodel'),
        ),
        migrations.CreateModel(
            name='PredefinedWorkoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('content', models.TextField()),
                ('workout_manual', models.TextField()),
                ('effects', models.TextField()),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('exercises', models.ManyToManyField(related_name='predefined_workout_exercises', to='exercises.exercisemodel')),
            ],
        ),
    ]
