# Generated by Django 5.1.3 on 2024-12-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_predefinedworkoutmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedworkoutmodel',
            name='image',
            field=models.ImageField(default='workouts_images/default_workout.jpg', upload_to='workouts_images/'),
        ),
    ]
