# Generated by Django 5.1.3 on 2024-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercisemodel_reps_exercisemodel_rest_and_more'),
        ('workouts', '0004_alter_customworkoutmodel_exercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedworkoutmodel',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, related_name='predefined_workout_exercises', to='exercises.exercisemodel'),
        ),
    ]
