# Generated by Django 5.1.3 on 2024-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercisemodel_reps_exercisemodel_rest_and_more'),
        ('workouts', '0005_alter_predefinedworkoutmodel_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedworkoutmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='predefinedworkoutmodel',
            name='exercises',
            field=models.ManyToManyField(related_name='predefined_workout_exercises', to='exercises.exercisemodel'),
        ),
    ]
