# Generated by Django 5.1.3 on 2024-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercisemodel_reps_exercisemodel_rest_and_more'),
        ('workouts', '0006_predefinedworkoutmodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedworkoutmodel',
            name='level',
            field=models.CharField(choices=[('B', 'Beginner'), ('A', 'Advanced'), ('I', 'Intermediate')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='predefinedworkoutmodel',
            name='training_type',
            field=models.CharField(choices=[('ST', 'Strength Training'), ('HIT', 'HIIT'), ('CT', 'Circuit Training'), ('BT', 'Bodyweight Training')], default='B', max_length=3),
        ),
        migrations.AlterField(
            model_name='predefinedworkoutmodel',
            name='exercises',
            field=models.ManyToManyField(to='exercises.exercisemodel'),
        ),
    ]
