# Generated by Django 5.1.3 on 2024-11-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_predefinedworkoutmodel_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedworkoutmodel',
            name='training_type',
            field=models.CharField(choices=[('ST', 'Strength Training'), ('HIT', 'HIIT'), ('CT', 'Circuit Training'), ('BT', 'Bodyweight Training')], max_length=3),
        ),
    ]
