# Generated by Django 5.1.3 on 2024-11-18 19:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('age', models.PositiveSmallIntegerField(error_messages={'max_value': 'You must be at most 100 years old.', 'min_value': 'You must be at least 10 years old.'}, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('height', models.PositiveSmallIntegerField(error_messages='Please provide correct height.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('goal', models.CharField(choices=[('FL', 'Fat Loss'), ('M', 'Maintenance'), ('MG', 'Muscle Gain')], max_length=2)),
                ('activity', models.CharField(choices=[('LA', 'Lightly Active (workouts not often with sedentary job)'), ('MA', 'Moderately Active (workouts often with sedentary job)'), ('VA', 'Very Active (workouts not often with active job)'), ('EA', 'Extremely Active (workouts often with active job)')], max_length=2)),
                ('daily_calories_need', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
