# Generated by Django 5.1.3 on 2024-12-14 06:51

import django.core.validators
import workoutPlanner.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), workoutPlanner.accounts.validators.OnlyLettersValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), workoutPlanner.accounts.validators.OnlyLettersValidator()]),
        ),
    ]
