# Generated by Django 5.1.3 on 2024-11-23 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_calories_need',
        ),
        migrations.AddField(
            model_name='profile',
            name='calories_needed',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(error_messages='Please provide correct height.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(error_messages='Weight cannot be negative number.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
