# Generated by Django 5.1.3 on 2024-12-14 10:18

import django.core.validators
import workoutPlanner.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), workoutPlanner.accounts.validators.OnlyLettersValidator('First name must contain only letters')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), workoutPlanner.accounts.validators.OnlyLettersValidator('Last name must contain only letters')]),
        ),
    ]
