# Generated by Django 5.1.3 on 2024-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_daily_calories_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calories_needed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
